---
title: "Preparing data for SDM intro - Yaguarundi in Latin America"
author: "Petr Keil, data from Florencia Grattarola"
date: "10/12/2022"
output: 
  html_document: 
    toc: yes
    highlight: pygments
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r, message = FALSE, warning=FALSE}
# GIS libraries
library(sp) # handling shapefiles, i.e. polygons, lines, and points
library(raster) # handling rasters
library(rgdal) # handling projections and spatial data

# modelling libraries
library(randomForest) # random forest machine learning
library(mgcv) # generalized additive models
library(dismo) # suite of SDM methods, including maxent

# miscelaneous libraries
library(tidyverse) # for ggplot, pipes, and all sorts of gymnastics
library(rJava) # this loads automatically with dismo, but sometimes it's missing
```

# Loading rasters and shapefiles

```{r maps, message=F}
# Defining the necessary projections
equalareaCRS <-  '+proj=laea +lon_0=-73.125 +lat_0=0 +datum=WGS84 +units=m +no_defs'
wgs84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "

# Loading border shapefiles
Latam <- readOGR(dsn="data", layer="Latam_vector")

Latam_countries <- readOGR(dsn="data", layer="Latam_vector_countries")

# Loading raster
Latam.raster <- raster('data/Latam_raster.tif')

# Loading IUCN range map
# IUCN. (2022). Herpailurus yagouaroundi (spatial data). International Union for Conservation of Nature. https://www.iucnredlist.org/species/9948/50653167
yaguarundi_IUCN <- readOGR(dsn='data', layer="yaguarundi_IUCN") %>% spTransform(CRSobj=equalareaCRS)
yaguarundi_IUCN.raster <- raster::rasterize(x = yaguarundi_IUCN,
                                            y = Latam.raster,
                                            field = 'presence') %>% mask(Latam.raster)


```

# Process the presence-absence data

```{r}
PA <- na.omit(readRDS("data/PA_post.RDs"))
PA <- select(PA, presabs, X, Y, area, effort, 
             env.elev, env.npp, 
             env.bio_1, env.bio_12, env.bio_7, env.bio_15) %>%
             mutate(log.area = log10(area),
                    log.effort = log10(effort))
```

# Process the presence-only data

```{r}
PO <- readRDS("data/PO_pre.RDs")
#PO <- na.omit(PO)
PO <- data.frame(presence = 0, PO)
PO$presence[PO$count > 0] <- 1
PO <- select(PO, presence, X, Y, area, pixel, acce, env.elev, 
             env.npp, env.bio_1, env.bio_12, env.bio_7, env.bio_15)
```

# Prepare the point data

```{r}
PTS <- read.csv("data/data_PO.csv")
PTS <- PTS[PTS$year <= 2013, ]
PTS <- SpatialPointsDataFrame(coords = PTS[,c("X", "Y")],
                                proj4string = CRS(wgs84),
                                data = PTS)
PTS <- spTransform(x=PTS, CRSobj=equalareaCRS)

plot(Latam)
plot(PTS,  col="red", add=TRUE)
```

# Presence-only data to raster stack

```{r}
PO.rasters <- Latam.raster
PO.rasters[PO$pixel] <- PO[,1]

for(i in 2:ncol(PO))
{
  rst <- Latam.raster
  rst[PO$pixel] <- PO[,i]
  PO.rasters <- stack(PO.rasters, rst)
}
names(PO.rasters) <- names(PO)

# subset of rasters that are predictors
PO.predictors <- PO.rasters[[6:11]]

plot(PO.rasters)
```

# Try maxent

```{r}
library(dismo)
mx <- maxent(x = PO.predictors, p = PTS)
predict.rast <- predict(mx, x = PO.predictors)
response(mx)

# check the predicted results
plot(predict.rast)
plot(yaguarundi_IUCN, col=NA, lwd=2, add=T)
plot(PTS, add=T)
```

# Save data to a file

```{r}
save(PA, PO,
     PO.rasters,
     PO.predictors,
     PTS, 
     yaguarundi_IUCN, yaguarundi_IUCN.raster, 
     Latam, Latam_countries, Latam.raster,
     
     file="yaguarundi_SDM_data.RData")
```
