---
title: "Introduction to Species Distribution Modelling (SDM) - data preparation"
author: "Petr Keil"
date: "10/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf); sf_use_s2(FALSE)
library(terra)
library(tidyverse)
library(randomForest)
library(mgcv)
```

```{r maps, message=F}
# Equal area projection
equalareaCRS <-  '+proj=laea +lon_0=-73.125 +lat_0=0 +datum=WGS84 +units=m +no_defs'
wgs84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
Latam <- st_read('data/Latam_vector.shp', quiet = T) %>% st_set_crs(equalareaCRS)
Latam_countries <- sf::st_read('data/Latam_vector_countries.shp', quiet = T) %>% st_set_crs(equalareaCRS)

Latam_no_islands <- bind_rows(list(Latam_countries %>%
                                     filter(type!='Indeterminate' & type!='Dependency' & type!='Lease') %>%
                                     mutate(iso_a2=ifelse(name_en=='France', 'GF', iso_a2)) %>%
                                     mutate(name_en=ifelse(name_en=='France', 'French Guiana', name_en)) %>%
                                     filter(!iso_a2 %in% c('EC','SX', 'NL', 'HT', 'DO', 'CU', 'CW', 'AW','BS', 
                                                           'TT', 'GD', 'VC', 'BB', 'LC', 'DM', 'AG', 'KN', 'JM')),
                                   Latam_countries %>%
                                     filter(name=='Ecuador') %>% 
                                     st_cast('POLYGON', quiet=T) %>% 
                                     mutate(area=st_area(.)) %>% arrange(desc(area)) %>% 
                                     head(n=1) %>% dplyr::select(-area))) %>% st_union()

Latam.raster <- terra::rast('data/Latam_raster.tif')

# IUCN. (2022). Herpailurus yagouaroundi (spatial data). International Union for Conservation of Nature. https://www.iucnredlist.org/species/9948/50653167
yaguarundi_IUCN <- sf::st_read('data/yaguarundi_IUCN.shp', quiet = T) %>% sf::st_transform(crs=equalareaCRS)
yaguarundi_IUCN.raster <- terra::rasterize(x = vect(yaguarundi_IUCN),
                                           y = Latam.raster,
                                           field = 'presence',
                                           fun = 'length', background=0) %>% mask(., Latam.raster)


```

# Process the presence-absence data

```{r}
PA <- na.omit(readRDS("data/PA_post.RDs"))
PA <- select(PA, presabs, X, Y, area, effort, 
             env.elev, env.npp, env.bio_7, env.bio_15)
```

# Process the presence-only data

```{r}
PO <- readRDS("data/PO_pre.RDs")
#PO <- na.omit(PO)
PO <- data.frame(presence = 0, PO)
PO$presence[PO$count > 0] <- 1
PO <- select(PO, presence, X, Y, pixel, acce, env.elev, env.npp, env.bio_7, env.bio_15)
```

# Presence-only data to raster stack

```{r}

PO.rasters <- Latam.raster
PO.rasters[PO$pixel] <- PO[,1]

for(i in 2:ncol(PO))
{
  rst <- Latam.raster
  rst[PO$pixel] <- PO[,i]
  PO.rasters <- c(PO.rasters, rst)
}
names(PO.rasters) <- names(PO)

plot(PO.rasters)
plot(Latam, add=T, col = NA)

PO.predictors <- PO.rasters[6:9]
plot(raster::stack(PO.predictors))

library(dismo)
maxent(x = raster::stack(PO.predictors), y = PTS)
```

# Select the interesting environmental predictors to

```{r}
predictors <- c("env.elev", "")
```


# Prepare the point data

```{r}
PTS <- read.csv("data/data_PO.csv")
PTS <- PTS[PTS$year <= 2013, ]
PTSsf <-st_as_sf(x = PTS, coords=c("X", "Y"), crs = wgs84)
PTS <- st_transform(x=PTSsf, crs=equalareaCRS )
plot(PTS,  col="black")
```


```{r}
plot(yaguarundi_IUCN.raster)
plot(yaguarundi_IUCN, col=NA, lwd=2, add=T)
points(shape12$X, shape12$Y)
```